### ISSUE TITLE
🪲[Bug]:  Static Copyright year

### ISSUE THREAD

**Issue by Meetjain1** [akshitagupta15june/PetMe-Prod#100]
**Describe the bug**
Currently copyright year is direct copy paste of text 

**To Reproduce**

**Expected behavior**
It should fetch the current year dynamically .

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

@akshitagupta15june assign this issue to me I will fix this , I am working under VSOC

**Comment by pratham-srivastava-07** [comment]
It's only about fixing the static copyright year to dynamic...right? @Meetjain1

**Comment by Meetjain1** [comment]
> It's only about fixing the static copyright year to dynamic...right? @Meetjain1

Yes

**Comment by pratham-srivastava-07** [comment]
okay then go ahead! @Meetjain1
