### ISSUE TITLE
Create Authentication Form Component for the frontend

### ISSUE THREAD

**Issue by cb7chaitanya** [akshitagupta15june/PetMe-Prod#13]
Component Design of Authentication Form for signup/login

**Comment by 0xaira** [comment]
Hi team,

I'd like to take on this issue (#13) to create the Authentication Form Component for the frontend. I have experience with building forms and handling authentication processes in previous projects, and I believe I can deliver a high-quality solution for this task. 

Looking forward to your approval so I can get started!

Thanks,
Aira

**Comment by Vrushti07** [comment]
Could you pls assign me this issue?

**Comment by gayatri-p786** [comment]
Hi, Can you please assign me this issue?

**Comment by cb7chaitanya** [comment]
@0xaira @gayatri-p786 @Vrushti07 We just want the component design and state logic for now, the bits about connecting it to the backend using axios comes later

I will leave it to you three to decide, who wants to do what and who gets to do what
I will assign it accordingly

**Comment by 0xaira** [comment]
https://github.com/akshitagupta15june/PetMe-Prod/pull/23

**Comment by cb7chaitanya** [comment]
@gayatri-p786 @Vrushti07 You both can work on this, first just ask how do you need to create this component in the discord channel, will give you the details

**Comment by kom-senapati** [comment]
Its 3 weeks and is not closed. If anyone is not working I can try to do this

**Comment by cb7chaitanya** [comment]
@kom-senapati Assigned

**Comment by kom-senapati** [comment]
# Screenshot of sample form components:
![image](https://github.com/akshitagupta15june/PetMe-Prod/assets/92045934/5d022a43-c0c5-4de2-a979-3f45ca03a5d9)
![image](https://github.com/akshitagupta15june/PetMe-Prod/assets/92045934/80c11854-432c-4df4-9dd3-b2f200a9c410)
