### ISSUE TITLE
I want to create Homepage 

### ISSUE THREAD

**Issue by divyansh2375** [akshitagupta15june/PetMe-Prod#2]

**Comment by cb7chaitanya** [comment]
Something specific you want to work on would be helpful, as you can see we have a homepage already

**Comment by divyansh2375** [comment]
for specific in the home page i want to change the colour of scroll bar according to homepagecolour
![image](https://github.com/akshitagupta15june/PetMe-Prod/assets/130889408/c252630f-569d-43f4-b931-7ae0568b7047)

**Comment by cb7chaitanya** [comment]
Do you want to report a UI bug or any other enhancement?

**Comment by dixitk941** [comment]
I want to work on this issue

**Comment by Nandhinirameshmala** [comment]
Assign this to me if possible

**Comment by cb7chaitanya** [comment]
This is not an issue for now guys, if anyone wants to suggest a major enhancement in the UI/UX or Bug fix, would assign them the issue
