### ISSUE TITLE
Fix typeerror in the google oauth 

### ISSUE THREAD

**Issue by Tanishq1604** [akshitagupta15june/PetMe-Prod#20]
in the app/petme-backend folder in app.ts in the password done function is giving type error fix it 
<img width="1470" alt="Screenshot 2024-06-08 at 7 33 35 AM" src="https://github.com/akshitagupta15june/PetMe-Prod/assets/139997424/1d7977db-9901-4a66-b277-85d3d0f1e5fa">
and i have added the comment there to fix it u just need to go to the app/PetMe-Backend folder and then go to app.ts and search for the comment

**Comment by Mrunalkhanke** [comment]
Intrested

**Comment by Khushi-S-29** [comment]
Please consider assigning this issue to me. I'm eager to work on it.

**Comment by cb7chaitanya** [comment]
@Mrunalkhanke Just a question, you would have your hands full with the other 2 PR's, so would it be ok if I assign this issue to @Khushi-S-29?

**Comment by Rishikesh63** [comment]
@cb7chaitanya  i wants to work on it  can you please assign to me

**Comment by Mrunalkhanke** [comment]
@cb7chaitanya , i would really like to work on this issue 😅

**Comment by cb7chaitanya** [comment]
@Mrunalkhanke Can you please communicate on the issues we have talked on first 

And @Rishikesh63, if @Khushi-S-29 doesn't get back to this issue, feel free to go ahead

**Comment by Mrunalkhanke** [comment]
@cb7chaitanya  , this was the only issue on which I droped comment, but I as you said it is assigned to khushi

**Comment by Khushi-S-29** [comment]
I will start working on it. Thank you

**Comment by cb7chaitanya** [comment]
Assigned, start working on it, ping me in discord if you have any doubt @Khushi-S-29 @Rishikesh63
