### ISSUE TITLE
implemention of signup and signin

### ISSUE THREAD

**Issue by Tanishq1604** [akshitagupta15june/PetMe-Prod#25]
add encryption /Hasing using bcrypt and jwt and add cookie-session  refer the api docs

**Comment by TammyAlok2** [comment]
Assign me the task

**Comment by Yashgupta9330** [comment]
Assign me

**Comment by Yashgupta9330** [comment]
I used jwt and brcypt many times

**Comment by Tanishq1604** [comment]
@Yashgupta9330 i have also assigned u the type error issue if no problem ,i think the issue should be assigned to @TammyAlok2 ?tell me

**Comment by Yashgupta9330** [comment]
Can this issue be assigned to me, and can the type error issue be assigned to @TammyAlok2 ?

**Comment by Tanishq1604** [comment]
@TammyAlok2 tell what u want to do ??

**Comment by TammyAlok2** [comment]
Give this Authentication task to me

**Comment by HemantKr071** [comment]
Hii @Tanishq1604 ,
I would like to work on this issue.
Please assign me.

**Comment by Yashgupta9330** [comment]
pls assign it to me I already said

**Comment by Tanishq1604** [comment]
ok so @HemantKr071 and @Yashgupta9330 can u work together then ??

**Comment by HemantKr071** [comment]
I have no issue, I can work together.

**Comment by Yashgupta9330** [comment]
Yes we can work together

**Comment by Tanishq1604** [comment]
Ok then assigning both of u, start working on it

**Comment by pratham-srivastava-07** [comment]
any updates on this!? @HemantKr071 and @Yashgupta9330

**Comment by Yashgupta9330** [comment]
Today, we will make a PR. Actually, exams are currently ongoing, that's  why we are late.

**Comment by Yashgupta9330** [comment]
I have made a pr
