### ISSUE TITLE
make a easy to understand Readme.mb file 

### ISSUE THREAD

**Issue by Tanishq1604** [akshitagupta15june/PetMe-Prod#26]
it will help contributer for better understanding of code flow and also help them setup the project locally via npm or docker

**Comment by kom-senapati** [comment]
I think it's a big project so we can have a simple readme about the project and demos.
For development specific we can have another readme to tell how to set up with npm or docker.

**Comment by cb7chaitanya** [comment]
@kom-senapati Yes we can have seperate markdown files, do you want this issue to be assigned to you?

**Comment by vishalmaurya850** [comment]
@cb7chaitanya Assign me this issue

**Comment by kom-senapati** [comment]
No I dont want the issue @vishalmaurya850  can do it.

**Comment by cb7chaitanya** [comment]
Great assigning it to @vishalmaurya850

**Comment by vishalmaurya850** [comment]
I am not getting the repository link. Please share @cb7chaitanya
