### ISSUE TITLE
Type error 

### ISSUE THREAD

**Issue by cb7chaitanya** [akshitagupta15june/PetMe-Prod#29]
Fix this type error
in src/app.ts in the backend folder 

Issue highlight:-
![Screenshot (22)](https://github.com/akshitagupta15june/PetMe-Prod/assets/114876060/8358af2d-6ab9-4b95-ae4a-b37d05528f8b)

**Comment by Yashgupta9330** [comment]
Assign me

**Comment by Tanishq1604** [comment]
go for it
