### ISSUE TITLE
Landing Page Enhancement:  UI Component of our Service in Home Page

### ISSUE THREAD

**Issue by Piyush-linux** [akshitagupta15june/PetMe-Prod#35]
> We shold have an  UI Component in Home Page of our service

__Inspiration__

![Screenshot_2024-06-09-20-22-27_1920x1080](https://github.com/akshitagupta15june/PetMe-Prod/assets/72852842/05bfcddc-a3b7-40b6-a2f1-7a0ee70f47c2)

### Additional Context
- I'm ready to work on this UI Component

**Comment by Mrunalkhanke** [comment]
@akshitagupta15june  I am interested to contribute to this issue

**Comment by Mrunalkhanke** [comment]
@Piyush-linux  intrested to contribute

**Comment by Piyush-linux** [comment]
@Mrunalkhanke yup
