### ISSUE TITLE
Constant Data : Consistent Link and Content

### ISSUE THREAD

**Issue by Piyush-linux** [akshitagupta15june/PetMe-Prod#37]
### Problem :fire: 
If an content needs some changes, we have to iterate through several folder to reach that page !
Even if an small link change :cry: 

### Expected Solution :rocket: 
- need of an `constant.js` to store all consistent data and link !

**Comment by cb7chaitanya** [comment]
Closing this for now, as we discussed an alternative for this, right? @Piyush-linux
