### ISSUE TITLE
Home Page UI Enhancemnet

### ISSUE THREAD

**Issue by Piyush-linux** [akshitagupta15june/PetMe-Prod#38]
### Description :spiral_notepad: 
- Need of an UI Component 
- Cards Component to showcase some options
- Under home page 

### Inspiration :framed_picture: 
![Screenshot_2024-06-09-23-01-23_1920x1080](https://github.com/akshitagupta15june/PetMe-Prod/assets/72852842/4c87a07f-d184-4459-9631-16d50b81af3b)

**Comment by cb7chaitanya** [comment]
Go for it, Would be sleek, just add a screenshot of the final thing once done as it is a UI component, okay?

**Comment by Piyush-linux** [comment]
Any problem @cb7chaitanya ?

**Comment by cb7chaitanya** [comment]
No problem go along with the component, that's all @Piyush-linux
