### ISSUE TITLE
UI: Contact Page From Scratch

### ISSUE THREAD

**Issue by Piyush-linux** [akshitagupta15june/PetMe-Prod#39]
### Problem :fire: 
- Need of an Contact Page from scratch
- Require Ideas and Content , we can discuss through it 

### Expected Solution :rocket: 
- Good UI
- meaningful content and section

> Reply on this if you have any Design , wireframe or concept .

**Comment by Piyush-linux** [comment]
### Componet
- [ ] Contact us Integration


![Screenshot_2024-06-09-23-13-56_1920x1080](https://github.com/akshitagupta15june/PetMe-Prod/assets/72852842/e3a47f11-5059-4cbb-9183-028ca8eb48f4)

**Comment by BhattAnsh** [comment]
Assigne me this issue

**Comment by karishmaaa101** [comment]
I would like to work upon this issue.Assign me.

**Comment by cb7chaitanya** [comment]
Looks great @Piyush-linux, would encourage you all to partner up on this @BhattAnsh @karishmaaa101 
Work on seperate components by taking this reference and coordinate

**Comment by Piyush-linux** [comment]
Sure

**Comment by cb7chaitanya** [comment]
Alright then assigning it to all of you

**Comment by cb7chaitanya** [comment]
@karishmaaa101 Are you working on this?

**Comment by karishmaaa101** [comment]
Yes I have started.

**Comment by cb7chaitanya** [comment]
@karishmaaa101 Just coordinate on this one with @BhattAnsh and @Piyush-linux to see how much of the work is done and how much is left, what do you have to do and all

**Comment by pratham-srivastava-07** [comment]
any updates!? @BhattAnsh @karishmaaa101

**Comment by BhattAnsh** [comment]
I've completed my contact page component already have a look 
![Screenshot 2024-06-10 123456](https://github.com/akshitagupta15june/PetMe-Prod/assets/97518515/be8aecd4-4c7d-42b9-b22e-b6343a9b77b2)
![Screenshot 2024-06-10 133119](https://github.com/akshitagupta15june/PetMe-Prod/assets/97518515/c4b92ea7-44c9-47a0-a0b9-c7728f18a00e)
![Screenshot 2024-06-10 133128](https://github.com/akshitagupta15june/PetMe-Prod/assets/97518515/ed4f64a6-88c9-4e5b-88e2-1c34f126da67)

**Comment by pratham-srivastava-07** [comment]
great @BhattAnsh

**Comment by karishmaaa101** [comment]
> any updates!? @BhattAnsh @karishmaaa101

I'm working on the "How Adoption works" page.

**Comment by pratham-srivastava-07** [comment]
okay....could you please give me an estimate on when the work will be completed?

**Comment by iamclintgeorge** [comment]
Can i work on the FAQs part? @pratham-srivastava-07

**Comment by pratham-srivastava-07** [comment]
yes! go ahead @BhattAnsh

**Comment by pratham-srivastava-07** [comment]
yup go ahead! @iamclintgeorge

**Comment by pratham-srivastava-07** [comment]
updates!? @karishmaaa101

**Comment by iamclintgeorge** [comment]
Sure, Thank you @pratham-srivastava-07

**Comment by karishmaaa101** [comment]
> any updates!? @BhattAnsh @karishmaaa101 
Open to feedbacks and suggestions.

![image](https://github.com/akshitagupta15june/PetMe-Prod/assets/104766763/5f1dbb5a-3794-45a0-a61a-a9612df54c3b)
