### ISSUE TITLE
[Docs]: Add Code of Conduct 

### ISSUE THREAD

**Issue by officeneerajsaini** [akshitagupta15june/PetMe-Prod#4]
scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by officeneerajsaini** [comment]
@akshitagupta15june i want to work on this issue under ssoc program.

**Comment by cb7chaitanya** [comment]
Add both code of conduct and issue template in one PR

**Comment by Khushi-S-29** [comment]
Please assign me this issue under  ssoc program. I would love to work on it.

**Comment by Priyanshu2631** [comment]
Please assign me this issue under SSOC'24

**Comment by cb7chaitanya** [comment]
@officeneerajsaini Any updates?
Or can i assign others willing to work on this?

**Comment by officeneerajsaini** [comment]
> Add both code of conduct and issue template in one PR
> 

Okay assign to me i will both in one pr

**Comment by cb7chaitanya** [comment]
Great start working on both @officeneerajsaini
