### ISSUE TITLE
UI: Blogs Page Enhancement

### ISSUE THREAD

**Issue by Piyush-linux** [akshitagupta15june/PetMe-Prod#40]
### Problem :fire: 
-  `/blogs` : Blogs page could be improved with proper styling
- Images are little stretched

### Expected Solution :rocket: 
- Card UI for blogs
- Good typography and spacing

**Comment by cb7chaitanya** [comment]
Go for it @Piyush-linux, the basic CRUD API endpoints are already merged and completed for this, so do tell what all you want to work with, like what scope
