### ISSUE TITLE
Need Readme file for repo

### ISSUE THREAD

**Issue by kapilG0** [akshitagupta15june/PetMe-Prod#45]
Read me file needs to be there for this repo

**Comment by kapilG0** [comment]
Hello @akshitagupta15june please assign this issue to me under gssoc

**Comment by pratham-srivastava-07** [comment]
updates!? @kapilG0

**Comment by cb7chaitanya** [comment]
Bro you have made a PR on your own fork, i think you did it by mistake 
@kapilG0

**Comment by kapilG0** [comment]
> Bro you have made a PR on your own fork, i think you did it by mistake @kapilG0

Yes sorry.
