### ISSUE TITLE
💡[FEATURE]: Create Detailed Pet About Page

### ISSUE THREAD

**Issue by Piyush-linux** [akshitagupta15june/PetMe-Prod#54]
:fire:   **Is your feature request related to a problem? Please describe.**
- Pets Gallery Page should have About detailed about page for every pet

:spiral_notepad:   **Describe the solution you'd like**
- Develop and implement a detailed web page for each pet
- Displaying comprehensive information about the pet.

:ballot_box_with_check:  **Tasks:**
- [ ] Design a structured and responsive layout.
- [ ] Ensure the pet's name is prominently displayed at the top.
- [ ] Create sections for age, gender, description, location, and images.
- [ ] Donate button
- [ ] Under `/pages` 
- [ ] Redirect from `Pets Gallery Page : UI Card`  

:framed_picture: **Inspiration**
![Screenshot_2024-06-12-11-58-24_1920x1080](https://github.com/akshitagupta15june/PetMe-Prod/assets/72852842/c14ca410-0b2d-48ef-bac5-fdbe5acf5621)

**Additional context**
> If any changes require plz don't hesitate to approach :smile:

**Comment by cb7chaitanya** [comment]
This I wanted to add as an issue, go for it form a team or something, I just need you to add one or two functionalities in it, I'll tel you in discord
