### ISSUE TITLE
💡[FEATURE]: Improve Footer UI

### ISSUE THREAD

**Issue by Piyush-linux** [akshitagupta15june/PetMe-Prod#57]
:fire: **Is your feature request related to a problem? Please describe.**
- Enhance the existing footer UI for better aesthetics and functionality.

:spiral_notepad:  **Describe the solution you'd like**
- [ ] Redesign footer layout.
- [ ] Update color scheme.
- [ ] Add links to important pages.
- [ ] Ensure responsiveness.

:framed_picture: **Inspiration**
![Screenshot_2024-06-13-14-52-05_1920x1080](https://github.com/akshitagupta15june/PetMe-Prod/assets/72852842/28bd7d4d-7714-4531-975a-53db5ede3a0f)

:package:  **Additional context**
> Attach screenshots about the feature request here.

**Comment by kom-senapati** [comment]
I would like to solve this if you tell me what footer contents you would like to have or replace from old one

**Comment by Piyush-linux** [comment]
Have you checked the existing Footer @kom-senapati  ?

**Comment by kom-senapati** [comment]
Yep

**Comment by Piyush-linux** [comment]
@kom-senapati 
So Create Accordingly by observing the Existing Site as well as the Inspired SS i've attached :smile:

**Comment by kom-senapati** [comment]
Will try to submit pr tomorrow
