### ISSUE TITLE
📝[Docs]: enhancing contact us page

### ISSUE THREAD

**Issue by Ayushswirlon** [akshitagupta15june/PetMe-Prod#70]
**What Docs changes are you proposing?**
the contact page is not that much eye catching 

**Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit the community?**
your website seems pretty much good but the contact us page seems to be off side . let me go through it and improve it.

**Describe the solution you'd like**
using some basic html css and js i am going to improve the visual appealing and some functioning properly.

**Describe alternatives you've considered**
If you've thought about alternative approaches or solutions, briefly describe them here.

**Additional context**
Add any additional context, examples, or screenshots related to the proposed documentation changes.

**Comment by cb7chaitanya** [comment]
We are not using HTML, CSS, JS is the only thing I would say, also as it is a UI issue why choose Docs template for presenting the issue, and provide screenshot of the issue you are describing @Ayushswirlon
