### ISSUE TITLE
🪲[Bug]: 

### ISSUE THREAD

**Issue by Harsha19-08** [akshitagupta15june/PetMe-Prod#81]
**Describe the bug**
Adding Images required images for the  Meet our Friend section 

**To Reproduce**
1. Go to Petme-pod website
2. Scroll down to 'Meet our friends  section
3. See error

**Expected behavior**
Representation of images 

**Screenshots**
![image](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/127961910/4491d498-650c-45d2-9a43-ae8983f9d079)

**Desktop (please complete the following information):**
 - OS: Windows
 - BrowserChrome

**Additional context**
@akshitagupta15june can u assign me this by SSOC so that i can work on it and can u give which type of images should be added

**Comment by pratham-srivastava-07** [comment]
@Harsha19-08  the issue you raised is caused by the fact that images should be provided by CDN or link, but here's what happening is people r using absolute path and some of those images will be uploaded by users.
