### ISSUE TITLE
💡[FEATURE]:  Enhancement of Homepage UI

### ISSUE THREAD

**Issue by Mehak-Mattoo** [akshitagupta15june/PetMe-Prod#84]
**Is your feature request related to a problem? Please describe.**
The current landing page indicates the website is only offering users to adopt a cat not other animals. 

**Describe the solution you'd like**
I can put up a cute landing page with carousel of animal pictures. 

**Describe alternatives you've considered**
I would like to put a clear concise heading in the landing page along with a animated animal gif. 

**Additional context**
Can you assign me this issue under VSOC. Thanks.

**Comment by cb7chaitanya** [comment]
Can you give us some refrences for it, like design ideas of what you want to achieve, would assign it to you afterwards @Mehak-Mattoo

**Comment by Mehak-Mattoo** [comment]
Sure, here are some of my design inspirations.

![original-5ace83b453238bc394426faea76e8f9a](https://github.com/akshitagupta15june/PetMe-Prod/assets/77096365/023bef14-21bc-43b1-8a37-5828ac7a699f)


The above design showcases all the features that a pet adoption site should cover and it is colorful that will really capture the eye of any user.

But i would rather use some different content for headings.

**Comment by cb7chaitanya** [comment]
@Mehak-Mattoo If you revamp the homepage UI, would you be willing to continue working on the UI of the other pages of the project, if so then it be a series of multiple PR's under VSOC because the UI has to be consistent

**Comment by Mehak-Mattoo** [comment]
Sure I can do that, given that I'll make the homepage the most attractive among the other pages and other pages would just follow the same color scheme and some animations, images etc.

**Comment by cb7chaitanya** [comment]
@Mehak-Mattoo Sure go ahead then, you can make a series of PR for this, all will be awarded under VSOC and if you have any doubt regarding anything, you can ping us on discord

**Comment by Mehak-Mattoo** [comment]
Sure

**Comment by cb7chaitanya** [comment]
Assigned @Mehak-Mattoo
