### ISSUE TITLE
🪲[Bug]: Pictures in homepage 

### ISSUE THREAD

**Issue by Mehak-Mattoo** [akshitagupta15june/PetMe-Prod#85]
**Describe the bug**
The images in the homepage are not loading 

**To Reproduce**
1. Go to 'landing page.'
2. Scroll down to second and third sections

**Expected behavior**
The pictures should load up as soon as the website loads or if the img size is large, it can be made smaller using online tools. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version [20]

**Smartphone (please complete the following information):**
 - Device: [Realme]
 - Browser [chrome ]

**Additional context**

**Comment by cb7chaitanya** [comment]
@Mehak-Mattoo Those images are a stopgap anyway, images on the website would mostly be inputs by the user which will be hosted on a S3 bucket, so no need for coming up with a solution for this, as it is just an issue where the static files(images) are not being served by a CDN

**Comment by Sarthak0085** [comment]
@cb7chaitanya  hey, i would like to work on this project can you assign me some backend and frontend tasks like contact us, adoption form or login, signup forms if required. Thanks!

**Comment by cb7chaitanya** [comment]
@Sarthak0085 You can raise new issues for the things you feel you can work on comment on existing issues if they have been abandoned, will assign you accordingly 
Other than that, you can ping us on discord
