### ISSUE TITLE
Created petme routes

### ISSUE THREAD

**Issue by udaynarwal72** [akshitagupta15june/PetMe-Prod#9]
pet routes needs to be created

**Comment by adarshawasthi29** [comment]
I can fixed that 
But i want some info regarding the complete functionality

**Comment by udaynarwal72** [comment]
> I can fixed that But i want some info regarding the complete functionality

for info connect with me on petme-backend discord

**Comment by INam1995** [comment]
@udaynarwal72 please assign this issue to me under ssoc I want to work upon this issue

**Comment by cb7chaitanya** [comment]
@INam1995 @adarshawasthi29 Decide who wants to pick this issue up, or if you want to split the issue and solve it together, i will assign accordingly

**Comment by adarshawasthi29** [comment]
I will do that just provide me the details that total how many functionalities are there.
if @INam1995  want to work along with me she can tell , otherwise @cb7chaitanya  you can assign it to me.

**Comment by cb7chaitanya** [comment]
You can start @adarshawasthi29 all the things you need to do are listed in the API doc in the readme, other than that you can ask Pratham and Uday in the discord as they have worked on rest of the Pet Routes

**Comment by pratham-srivastava-07** [comment]
@adarshawasthi29 only one petMeRoute is remaining, i.e /:petId/adopt. You can work upon that, make sure to git pull first because I have created the SOS as well as donate endpoints. Reach out to me or @udaynarwal72 if there's any doubt about the approach

**Comment by pratham-srivastava-07** [comment]
any updates? @adarshawasthi29
